name: Multi Jobs file

on: push

jobs:
    build_job:
        runs-on: ubuntu-latest
        steps:
            - name: Install cowsay program
              run: sudo apt-get install cowsay -y
            
            - name: Executing Cowsay CMD
              run: cowsay -f dragon "Run for Cover, I am a DRAGON...RAWR" >> dragon.txt
  
            - name: Upload the Artifact
              uses: actions/upload-artifact@v4
              with:
                name: dragon file artifact
                path: dragon.txt
              

    test_job:
        needs: build_job
        runs-on: ubuntu-latest
        steps:
            - name: Upload the Artifact
              uses: actions/download-artifact@v4 
              with:
                name: dragon file artifact
                    
            - name: Test File exists
              run: grep -i "dragon" dragon.txt         
                       
    deploy_job:
        needs: test_job
        runs-on: ubuntu-latest
        steps:
          - name: Upload the Artifact
            uses: actions/download-artifact@v4 
            with:
                name: dragon file artifact
          
          - name: Read File
            run: cat dragon.txt
                            
          - name: Deploy
            run: echo Deploying ... .. .