name: context testing

on: 
    push

jobs:
    dump-context-to-log:
        runs-on: ubuntu-latest
        steps:
            - name: Dum Github context
              env:
                 GITHUB_CONTEXT: ${{ toJson(github)}}
              run: echo "$GITHUB_CONTEXT"
            
            - name: Dum Job context
              env:
               JOB_CONTEXT: ${{ toJson(job)}}
              run: echo "$JOB_CONTEXT"
            
            - name: Dum Step context
              env:
               STEP_CONTEXT: ${{ toJson(steps)}}
              run: echo "$STEP_CONTEXT"

            - name: Dum Runner context
              env:
                 RUNNER_CONTEXT: ${{ toJson(runner)}}
              run: echo "$Runner_CONTEXT"

            - name: Dum Secrets context
              env:
                 SECRETS_CONTEXT: ${{ toJson(secrets)}}
              run: echo "$SECRETS_CONTEXT"



