    #environmet variable at step level
# name: Exploring Variable and Scerets

# on:
#      push

# jobs:

#     docker:
#       runs-on: ubuntu-latest
#       steps:
#         - name: docker-build
#           env:
#             CONTAINER_REGISTRY: docker.io
#             DOCKER_USERNAME: malikyasin
#             IMAGE_NAME: react-app-image
#           run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
        
#         - name: Docker login
#           env:
#             DOCKER_PASSWORD: realdocker1
#             DOCKER_USERNAME: malikyasin
#           run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
          
#         - name: Docker Publish  
#           env:
#             CONTAINER_REGISTRY: docker.io
#             DOCKER_USERNAME: malikyasin
#             IMAGE_NAME: react-app-image
#           run: echo docker push -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

#     deploy:
#         needs: docker
#         runs-on: ubuntu-latest
#         steps:
#         - name: Docker Run
#           env:
#             CONTAINER_REGISTRY: docker.io
#             DOCKER_USERNAME: malikyasin
#             IMAGE_NAME: react-app-image
#           run: echo docker run -d -p $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest



   # environmet variable at Job level
#    name: Exploring Variable and Secrets

#    on:
#      push
   
#    jobs:
#      docker:
#         env:
#            CONTAINER_REGISTRY: docker.io
#            DOCKER_USERNAME: malikyasin
#            IMAGE_NAME: react-app-image
#            DOCKER_PASSWORD: realdocker1

#         runs-on: ubuntu-latest
#         steps:
#          - name: Docker Build
#            run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
   
#          - name: Docker Login
           
             
#            run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
   
#          - name: Docker Publish
#            run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
   
#      deploy:
#         env:
#            CONTAINER_REGISTRY: docker.io
#            DOCKER_USERNAME: malikyasin
#            IMAGE_NAME: react-app-image
#         needs: docker
#         runs-on: ubuntu-latest
#         steps:
#          - name: Docker Run
#            run: echo docker run -d -p 80:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
   
   # environmet variable at workflow level level
    name: Exploring Variable and Secrets

    on:
      push

    env:
        CONTAINER_REGISTRY: docker.io
        DOCKER_USERNAME: malikyasin
        IMAGE_NAME: react-app-image
        DOCKER_PASSWORD: realdocker1
    
    jobs:
      docker:
        runs-on: ubuntu-latest
        steps:
          - name: Docker Build
            run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
    
          - name: Docker Login
            run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
    
          - name: Docker Publish
            env:
              CONTAINER_REGISTRY: docker.io
              DOCKER_USERNAME: malikyasin
              IMAGE_NAME: react-app-image
            run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
    
      deploy:
        needs: docker
        runs-on: ubuntu-latest
        steps:
          - name: Docker Run
            run: echo docker run -d -p 80:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
    