name: Generate ASCII Artwork

on: push

jobs:
    ascii_jobs:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
              
            - name: Chectout Repo files
              run: ls -ltra
              
            - name: Excute Shell Script
              run: ./ascii-script.sh
            
            
