name: Generate ASCII Artwork

on: push

jobs:
    ascii_jobs:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
            
            - name: Chectout Repo files
              run: ls -ltra
  
            - name: Executing shell script
              run: |
               chmod +x ascii-script.sh
               ./ascii-script.sh